version: "2"
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 40
plugins:
    stylelint:
        enabled: true
    duplication:
        enabled: true
        checks:
            Similar code:
                enabled: false    
        config:
            languages:
                - javascript
                - php
    fixme:
        enabled: true
    phpmd:
        enabled: true
        config:
            file_extensions: "php"
            rulesets: "yii.xml"
ratings:
    paths:
        - "**.less"
        - "**.css"
        - "**.js"
        - "**.php"
exclude_paths:
    - bin/
    - config/
    - docs/
    - runtime/
    - tests/